### ISSUE TITLE
What is the correct TERM?

### ISSUE THREAD

**Issue by arp242** [aaronjanse/3mux#17] opened 2020-04-12 10:45 UTC
Things like arrow keys and delete button don't seem to work correct in either `st` or `xterm`. I suspect this is probably related to an incorrect `TERM`(?) But I couldn't find what the correct one should be? Would be helpful if this was documented instead of trying a few until one works!

**Comment by aaronjanse** [comment] 2020-04-12 21:19
I just fixed the delete key on xterm. https://github.com/aaronjanse/3mux/commit/31af1e219d1164ec1862bce3229189b1b88ad927
St seems more complex to deal with, though. http://git.suckless.org/st/file/FAQ.html#l25

I couldn't reproduce arrow key issues on xterm or st (under Linux). Are you using macOS?

---

The truth is, $TERM isn't used, and this is a problem. I originally didn't use ncurses after reading some outdated documentation. I plan on re-implementing keypress reading and rendering using ncurses later this week.

I'll also look into how tmux deals with `st`.

**Comment by arp242** [comment] 2020-04-13 04:00
Nah, I use Linux (do xterm and st even run on macOS?)

Actually the arrow keys work in zsh, but not in Vim; this is probably a Vim issue, but I thought it could probably be fixed with some TERM frobbing 😅

There's also an issue with colours, notice how the tabline and statusline aren't inversed:

![screenshot_2020-04-13-11-55-05](https://user-images.githubusercontent.com/1032692/79090889-bdfbc800-7d7d-11ea-82b0-963f90545bb5.png)

It has `cterm=bold,reverse`; so looks like that's not supported perhaps? I don't envy you for dealing with all this terminal stuff by the way, it's hard stuff.

Also: I just casually looked at this program, I'm probably not going to use it, as I don't really use panes with tmux (or use i3), so the advantages of this project are kinda lost for me; so please don't hurry to fix/change anything on my regard; just so you know. I just figured this might be a common issue/question so it would be helpful to open an issue for this. Don't mind help testing stuff if that's helpful for you though.

**Comment by aaronjanse** [comment] 2020-04-13 04:45
Oh wow. I've been dealing with the vim bug for the past hour in a different branch. I didn't realize the regression happened on master. I just fixed the issue, and you can update 3mux via `go get -u github.com/aaronjanse/3mux`.

> It has cterm=bold,reverse; so looks like that's not supported perhaps?

Not yet, but it's an easy fix. I'm refactoring the rendering engine right now (https://github.com/aaronjanse/3mux/issues/21), so I'll make sure to include this feature.

> I just casually looked at this program, I'm probably not going to use it, as I don't really use panes with tmux (or use i3), so the advantages of this project are kinda lost for me; so please don't hurry to fix/change anything on my regard. Just so you know. I just figured this might be a common issue/question so it would be helpful to open an issue for this. Don't mind help testing stuff if that's helpful for you though (or feel free to just close this).

No problem, and thank you so much! I'm going to close this specific issue, but if you've notice anything else weird, feel free to open another issue or leave a comment here.

**Closed by aaronjanse** 2020-04-13 04:45 UTC
