### ISSUE TITLE
Error on macOS 10.14.6

### ISSUE THREAD

**Issue by carlca** [aaronjanse/3mux#4] opened 2020-04-09 13:15 UTC
- Mac Pro (early 2009)
- macOS 10.14.6
- go version go1.14.1 darwin/amd64
- Shell - Alacrity + ZSH (not with OhMyZSH!) 
- Same error occurs with iTerm and Terminal

`go get github.com/aaronjanse/3mux` completes okay
but `3mux` [enter] gives the following...

Stack trace...
```
Error during: pane.go (shell death)
runtime error: index out of range [0] with length 0
Tiling state: Universe[0](Workspace(HSplit[0](Term[160x49]*)))
goroutine 51 [running]:
runtime/debug.Stack(0x1180c60, 0xc00000e018, 0xc0000a6cf8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
main.fatalShutdownNow(0xc000016140, 0x49)
	/Users/carlca/Code/go/src/github.com/aaronjanse/3mux/main.go:126 +0x16c
main.newTerm.func2.1()
	/Users/carlca/Code/go/src/github.com/aaronjanse/3mux/pane.go:68 +0xb3
panic(0x1144500, 0xc0001a8040)
	/usr/local/go/src/runtime/panic.go:967 +0x166
main.newTerm.func2(0xc00007e000)
	/Users/carlca/Code/go/src/github.com/aaronjanse/3mux/pane.go:74 +0x230
created by main.newTerm
	/Users/carlca/Code/go/src/github.com/aaronjanse/3mux/pane.go:65 +0x167


Please submit a bug report with this stack trace to https://github.com/aaronjanse/3mux/issues
```

**Comment by aaronjanse** [comment] 2020-04-10 00:49
Thank you for the detailed bug report! I think I [figured out the problem](https://github.com/aaronjanse/3mux/commit/afc1a2a1cb9da3c0c7c2b7a71de93088f06c8316).
Would you mind updating `3mux` and seeing if it works?

```bash
$ go get -u github.com/aaronjanse/3mux
$ 3mux
```

**Comment by carlca** [comment] 2020-04-10 10:57
Vast improvement 😀 Although when I press `3mux` [enter], there is a brief flash of the lime status bar at the bottom, then it disappears. I then do a single carriage return and it appears again. Thereafter, it seems to behave as it should do.

I do notice, however, that the cursor is flashing in a less than healthy way.
Also, when I type `exit` in order to close `3mux`, I see this...

![Screenshot 2020-04-10 at 11 53 14](https://user-images.githubusercontent.com/260612/78985953-0323be00-7b22-11ea-82e5-3ab74e1b5ffa.png)

Attempts to select the screen using the mouse result in the control characters shown under the stack trace in the image, hence why I had to use a screenshot rather than text copy/paste!

**Comment by aaronjanse** [comment] 2020-04-10 21:03
> Although when I press 3mux [enter], there is a brief flash of the lime status bar at the bottom, then it disappears. I then do a single carriage return and it appears again. Thereafter, it seems to behave as it should do.

I'm still trying to reproduce this issue. Long-term, though, I should probably move 3mux's rendering backend to ncurses. I'm hesitant to do so because it would make 3mux's codebase much more boring, but oh well. Regardless, I'm excited to see people other than myself using 3mux!

> I do notice, however, that the cursor is flashing in a less than healthy way.

Fixed by https://github.com/aaronjanse/3mux/commit/22cb30d5ea2369d414824c93307e78ba7fe01a1b.

> Also, when I type exit in order to close 3mux, I see this...
> [Screenshot]

Fixed by https://github.com/aaronjanse/3mux/commit/60f0d6ab8a0e500e8099e63d6bd4dd72597f4365

> Attempts to select the screen using the mouse result in the control characters shown under the stack trace in the image, hence why I had to use a screenshot rather than text copy/paste!

Fixed. This was caused by two problems:
1. Mouse actions are captured when only a single pane is open (should not happen; tracked by https://github.com/aaronjanse/3mux/issues/9)
2. Shell panic recovery did not gracefully shutdown 3mux (fixed by https://github.com/aaronjanse/3mux/commit/0b7099c7a08ef375015143c4e6a9b15d17ddfe5c)

---

P.S. You've got an awesome-looking theme and prompt in your screenshot there!

I use Alacritty myself, and a few minutes ago I added support for iTerm2. Sadly, Terminal.app doesn't seem to distinguish Alt+Arrow from Alt+Shift+Arrow, so I've added a warning to the README suggesting that Terminal.app users use the available vim-like keybindings to manage windows.

**Comment by carlca** [comment] 2020-04-10 21:58
Hi Aaron,

Thanks for the quick turn around!

The first issue does't occur any more, as far as I can tell, and the other
fixes all appear to be okay as well 😀

Yeah, the theme is an attempt by me to reproduce the color settings I had
in iTerm. It’s close enough, I think.

As I mentioned in my initial bug report, I use ZSH but rather than OhMyZSH,
I use Prezto https://github.com/sorin-ionescu/prezto because it’s much
faster than OhMyZSH. The elected theme is the Prezto author’s own “Sorin”
theme.

Another neat thing on my machine is a Golang app called `ls-go`
https://github.com/acarl005/ls-go. I’ve got it aliased to `ll` and it gives
me listings like this…

One small problem still remains. I’m still getting lots of weird control
codes showing up when I manipulate the mouse.

Cheers,
Carl


On 10 April 2020 at 22:04:06, Aaron Janse (notifications@github.com) wrote:

Although when I press 3mux [enter], there is a brief flash of the lime
status bar at the bottom, then it disappears. I then do a single carriage
return and it appears again. Thereafter, it seems to behave as it should do.

I'm still trying to reproduce this issue. Long-term, though, I should
probably move 3mux's rendering backend to ncurses. I'm hesitant to do so
because it would make 3mux's codebase much more boring, but oh well.
Regardless, I'm excited to see people other than myself using 3mux!

I do notice, however, that the cursor is flashing in a less than healthy
way.

Fixed by 22cb30d
<https://github.com/aaronjanse/3mux/commit/22cb30d5ea2369d414824c93307e78ba7fe01a1b>
.

Also, when I type exit in order to close 3mux, I see this...
[Screenshot]

Fixed by 60f0d6a
<https://github.com/aaronjanse/3mux/commit/60f0d6ab8a0e500e8099e63d6bd4dd72597f4365>

Attempts to select the screen using the mouse result in the control
characters shown under the stack trace in the image, hence why I had to use
a screenshot rather than text copy/paste!

Fixed. This was caused by two problems:

   1. Mouse actions are captured when only a single pane is open (should
   not happen; tracked by #9 <https://github.com/aaronjanse/3mux/issues/9>)
   2. Shell panic recovery did not gracefully shutdown 3mux (fixed by
   0b7099c
   <https://github.com/aaronjanse/3mux/commit/0b7099c7a08ef375015143c4e6a9b15d17ddfe5c>
   )

------------------------------

P.S. You've got an awesome-looking theme and prompt in your screenshot
there!

I use Alacritty myself, and a few minutes ago I added support for iTerm2.
Sadly, Terminal.app doesn't seem to distinguish Alt+Arrow from
Alt+Shift+Arrow, so I've added a warning to the README suggesting that
Terminal.app users use the available vim-like keybindings to manage windows.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aaronjanse/3mux/issues/4#issuecomment-612216916>, or
unsubscribe

**Comment by aaronjanse** [comment] 2020-04-11 02:46
> Yeah, the theme is an attempt by me to reproduce the color settings I had in iTerm. It’s close enough, I think.

It looks beautiful. Thanks for the heads-up about ls-go and prezto! I'll definitely try those out.

> One small problem still remains. I’m still getting lots of weird control codes showing up when I manipulate the mouse.

Weird. Do those control codes end with an "M"?

**Comment by aaronjanse** [comment] 2020-04-11 04:09
I just pushed some more code. Would you mind updating with `go get -u github.com/aaronjanse/3mux` and seeing if you still have the mouse issue?

Cheers,
Aaron

**Comment by carlca** [comment] 2020-04-11 08:41
By Jove! I think you've cracked it! No weird errors when typing `exit()` and behaviour as expected from a mouse point-of-view.  Thanks for sorting this, Aaron!
Cheers,
Carl

**Comment by aaronjanse** [comment] 2020-04-11 09:17
Thanks for the helpful bug reports!

**Closed by aaronjanse** 2020-04-11 09:17 UTC
